### ISSUE TITLE
App closes itself when updating while GW2 is running

### ISSUE THREAD

**Issue by arjendejong12** [fmmmlee/GW2-Addon-Manager#1]
Hey, I had an ArcDPS update but while updating, the program just closes itself. I was wondering why, but I forgot I had GW2 already running, so closing that and then running the updater made it work again. Could you maybe show a message that GW2 needs to be closed while running the updater?

**Comment by fmmmlee** [comment]
Good point, you running the latest version? I thought it would have caught the exception and shown you an error message before closing, but adding more descriptive, specific error messages (and enclosing stuff in try/catch blocks so things can be retried) is on my list of things to add.

**Comment by arjendejong12** [comment]
I was running v0.3.3 so I updated to v0.4.1 thinking maybe it was a version error. I'm glad it's on the list. :)

**Comment by fmmmlee** [comment]
Hm, 0.3.3 should have had the exception handling - did the crash get put in the log file?

**Comment by arjendejong12** [comment]
I don't see any log file in my directory where I've saved the files.

**Comment by fmmmlee** [comment]
yeah, the logging and exception message are part of the same action, so if one doesn't trigger the other one probably didn't; just wanted to confirm. I'll have to test this myself and see if I can reproduce the issue. I did also add a "don't run this while GW2 is running" thing to the readme a few commits ago, but earlier users wouldn't see that

**Comment by fmmmlee** [comment]
the readme indicates this and I might add a dialog box/popup with info on the user's first run in 0.5.x
