### ISSUE TITLE
addon downloaded all the mods, but none work in game

### ISSUE THREAD

**Issue by gunnho** [fmmmlee/GW2-Addon-Manager#10]
your manager created all the folders for the mods, but didnt create a d3d9.dll file anywhere, so i downloaded it from delta and placed it in my bin64 folder, and arcdps now loads on its on, but no other mods load. no keyboard shortcuts will load radial

**Comment by fmmmlee** [comment]
Was this on the alpha version or version 0.4.5?

**Comment by gunnho** [comment]
GW2 UOAOM v1.0.0 latest

**Comment by fmmmlee** [comment]
So yeah, the prerelease. It *should* download the d3d9.dll file from https://github.com/gw2-addon-loader/loader-core. Can I see your config.yaml file?

**Comment by gunnho** [comment]
application_version: v1.0.0
loader_version: v0.1
bin_folder: bin64
isupdate: true
game_path: C:\Guild Wars 2
default_configuration:
  d3d9_wrapper: false
version:
  d3d9_wrapper: v1.0
  arcdps: >
    6bd045305a6b689f60c536e72c6f3f4c  x64/d3d9.dll
  arcdps_bhud: v0.2.4
  gw2radial: v1.2.4_al
  arcdps_mechanics: >+
    39af47dea0d955e181aea205c0ec6a7c

  d912pxy: v1.9h2
installed:
  d3d9_wrapper: d3d9_wrapper
  arcdps: arcdps
  arcdps_bhud: arcdps_bhud
  gw2radial: gw2radial
  arcdps_mechanics: arcdps_mechanics
  d912pxy: d912pxy
disabled:
  d3d9_wrapper: false
  arcdps: false
  arcdps_bhud: false
  gw2radial: false
  arcdps_mechanics: false
  d912pxy: false

**Comment by fmmmlee** [comment]
Interesting...it says loader version v0.1, so it *should* have placed a d3d9.dll from the url I linked into the bin64 folder. You could manually use the release from https://github.com/gw2-addon-loader/loader-core/releases and stick it in /bin64/ yourself, or you could try setting this line:

`loader_version: v0.1`

to 

`loader_version:`

and re-running the manager and hitting 'update'. If that doesn't work, I'll do some testing myself on my machine and get back to you.

**Comment by gunnho** [comment]
that worked, thanks! any chance of some kind of gw2hook functionality, all i want is fog removal

**Comment by gunnho** [comment]
actually, mounts and proxy work, but now arcdps doesnt

**Comment by fmmmlee** [comment]
did you install arc through the manager? there should be an /addons/arcdps folder with gw2addon_arcdps.dll inside it if you did.

**Comment by gunnho** [comment]
yes, and i deleted my manually downloaded d3d9, removed v0.1 again and updated via the manager, it added d3d9 its self, again, proxy and radial do load, but not arcdps

**Comment by fmmmlee** [comment]
That's weird; can I see a screenshot of /addons/arcdps?

**Comment by gunnho** [comment]
https://imgur.com/tszrxRh

**Comment by gunnho** [comment]
the arcdps buildpad/templates was working before i decided to try your manager

**Comment by fmmmlee** [comment]
as the [release page says](https://github.com/fmmmlee/GW2-Addon-Manager/releases/tag/v1.0.0-al), currently addons dependent on arcdps aren't working. I think if just gw2addon_arcdps.dll is in that folder Arcdps should work.

**Comment by fmmmlee** [comment]
I'm hoping to get the dependent addons working soon, though - I believe it's a change to plugin searcfh locations that Deltaconnected would have to make in Arcdps itself.

**Comment by gunnho** [comment]
youre right, i removed the buildpad/templates folder and all works fine now, and while buildpad still loads in arcdps, i have lost access to my old templates files. nevermind, i can revert everything, save the old templates into anets new templates, and delete my old backups and have it all running again.

thanks again

**Comment by fmmmlee** [comment]
No problem - if you feel like trying it it, the last full release, [0.4.5](https://github.com/fmmmlee/GW2-Addon-Manager/releases/tag/v0.4.5), should probably work with all the things you're using (it still uses traditional chainloading, which most of the development community was using before megai2 released the addon loader).
