### ISSUE TITLE
imgui version mismatch

### ISSUE THREAD

**Issue by voliva** [fmmmlee/GW2-Addon-Manager#101]
After updating ArcDPS to the latest version there's a couple of arcdps addons that fail to load:

```
warning: failed to load "d3d9_arcdps_table.dll", reason: imgui version mismatch
warning: failed to load "d3d9_arcdps_mechanics.dll", reason: imgui version mismatch
```

(Boon table and mechanics respectively)

I've digged on the boon table, there's an issue on the original repo https://github.com/MarsEdge/GW2-ArcDPS-Boon-Table/issues/4 which points that the original repo is no longer mantained, and now has moved to https://github.com/knoxfighter/GW2-ArcDPS-Boon-Table/ which looks like it's in active development (so probably that one would work?)

However, it seems like Gw2-AoM is using another fork of the original repo which hasn't been updated for a while: https://github.com/gw2-addon-loader/GW2-ArcDPS-Boon-Table

Would it be posible to update those two addons to use the latest changes?

**Comment by deadpyxel** [comment]
Same thing has been happening to me. I do believe this is due to the mentioned desynced forks.

**Comment by Draeggiar** [comment]
As far as i know Addon manager uses the knoxfighter repo you mentioned. UOAM addons sources are located in https://github.com/gw2-addon-loader/Approved-Addons

**Comment by voliva** [comment]
> As far as i know Addon manager uses the knoxfighter repo you mentioned. UOAM addons sources are located in https://github.com/gw2-addon-loader/Approved-Addons

Ah that's absolutely right - it was updated earlier this year on https://github.com/gw2-addon-loader/Approved-Addons/pull/8

But the latest release doesn't include these changes, right?

I'll try manually updating the .yaml file

**Comment by deadpyxel** [comment]
I checked my local boontable YAML, and it seems to be pointing to the correct repo. Is there anything else I can check to see why that message is appearing? I was thinking of reinstalling the boontable addon, but not sure if that will help (like caching or something).

**Comment by deadpyxel** [comment]
An UPDATE: I did a "Hard-reset" (clean-install + reinstall all addons) and it seems that the warning is gone. Is there a possibility something is getting cached somewhere?

**Comment by voliva** [comment]
> An UPDATE: I did a "Hard-reset" (clean-install + reinstall all addons) and it seems that the warning is gone. Is there a possibility something is getting cached somewhere?

Yep, that did it too for me - Redownloaded v1.3.0, deleted previous AoM installation and replaced with the fresh new patch, reinstalled everything and it works fine 🎉 

I didn't remove the old arcdps plugnis (just hit update) and it kept my config too. I'll close this issue, I think the clean reinstall fix is simple enough.
