### ISSUE TITLE
d9vk addon support ?

### ISSUE THREAD

**Issue by nykoo** [fmmmlee/GW2-Addon-Manager#11]
Hi, 

Thank you for this great addon idea that's seems really interesting.

Do you think you can add d9vk addon support (as d912pxy cause lots of problem with my RT 5700 Xt and d9vk  working simply great)

here is the link for last d9vk : https://git.froggi.es/joshua/d9vk/-/jobs
link to d9vk github : https://github.com/Joshua-Ashton/d9vk   (but last version need to be download from previous link in git.froggi)

Thank you :)

**Comment by fmmmlee** [comment]
Hey there! I'll keep this on my radar.

For it to work with the next version it has to be compatible with the [addon loader ](https://github.com/gw2-addon-loader/loader-core), for which it has to have some particular information exposed to the loader API. If you like, you could contact the creator of d9vk and ask for that compatibility to be added, or it's possible that someone else could fork it and add it themselves.

**Comment by nykoo** [comment]
Thank you for your answer, i will transmit to d9vk creator :)

**Comment by Joshua-Ashton** [comment]
Yeah, implementing this in D9VK isn't going to happen.
But, there is a **better solution**!

This could be done simply by editing the loader:

https://github.com/gw2-addon-loader/loader-core/blob/2c9ab2b1595e750f5cb30901c7d800fda46e1690/loader_core/loader_core.cpp#L110

Add an option to read an env var for the D3D9 dll path override, that way you could just use d912pxy, d9vk or native (ie. fallback to system path if not specified).

This would separate the addon loader and the renderer.

**Alternatively** you could hook any other DLL that isn't d3d9 to do this with.

Anyway, this would be something @megai2 would need to do.

**Comment by seanbarr1988** [comment]
was this issue ever resolved? would like to have DXVK support if possible 👍
