### ISSUE TITLE
Configuration Options not working

### ISSUE THREAD

**Issue by Elosy** [fmmmlee/GW2-Addon-Manager#118]
**Describe the bug**
"Configuration Options" drop down menu options not working, except "Reset to Clean Install"; can't Delete, Disable or Re-Enable.
![image](https://user-images.githubusercontent.com/68139545/126274568-0c82e831-628f-49f4-8e68-d883db35a36b.png)

**To Reproduce**
Select addons, try to Delete.

**Additional context**
I have tried multiple folders, executing as administrator and redownloading.

(i couldn't find configs with .yaml or .ini, it was .xml)
(changed to .txt cause it won't let me upload)
[config.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/6846071/config.txt)

**Comment by kazerniel** [comment]
Sadly this has been broken for a while: #95
