### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Itamik0** [fmmmlee/GW2-Addon-Manager#123]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
After adding and removing 2 add ons with the manager, i get the error 403 after trying to open the addon manager.

an unhandled exception occured.
After call of constructor for type "GW2_addon_manager.openingview, an exception has occured. Remoteserver error 403

[log.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/7003388/log.txt)

**To Reproduce**
I wish I know all the steps, but I cant tell for sure.

**Additional context**
No add on can be added to the game, since the manager is not working 

**don't forget to attach the config file to the issue**

I can not find any config file

**Comment by ALERTua** [comment]
same here
![image](https://user-images.githubusercontent.com/8375129/133209684-2ecc127e-7bf6-47c5-bf8a-30fc20055d14.png)
