### ISSUE TITLE
Unable to Launch "Unable to initialize 3d output"

### ISSUE THREAD

**Issue by alzatar** [fmmmlee/GW2-Addon-Manager#14]
### Please attach a copy of config.yaml or config.ini to the issue.
I was using .45 and reshade 4.5.3.  I had no issues for the week of use.  Yesterday evening I could no longer launch the game.  When you hit play it says unable to initialize 3d output.  Please verify you have installed directx 9 and updated video driver.  I have a windows 10 dell g7 laptop.  I did deleted everything except the dat file and reloaded the game just fine.  I redownloaded the lastest 1.0 version and without installing reshade it gives me the same error again.   Really love the d912 app etc it makes the game run better.  Im no programmer but if you tell me how to get the info you need i can manage just fine.  
A text file in the gw2 folder 
[INFO] core | Addon loader v0.1 (v0.1 r11) loaded
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v1.0 r6
[INFO] core | Loaded arcdps v1.0 r322
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading d912pxy
[INFO] core | Loaded d912pxy v2.0 r493
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v1.2 r6
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading custom lib from D3D_wrapper_custom_d3d9_lib_query
[INFO] d3d9_wrapper | d3d9 library failed to load
[INFO] core | Exiting, unloading core addon
[ERR] core | Some addons are not unloaded!
[INFO] core | Unloaded

**Comment by fmmmlee** [comment]
As per the issue template:
**don't forget to attach the config file to the issue**

The config.yaml file should be wherever you installed the addon manager. When you deleted things, where did you do the deleting (just in bin64 folder or other places too)?

Hard to say without the config file, but it sounds like this could be a problem with interactions between d192pxy and reshade. @Megai2 any insights?

**Comment by alzatar** [comment]
application_version: v1.0.0
loader_version: v0.1
bin_folder: bin64
isupdate: true
game_path: C:\Program Files\Guild Wars 2
default_configuration:
  d3d9_wrapper: false
version:
  d3d9_wrapper: v1.0
  arcdps: >
    df71ea0e8c25aa7bc0f37d2b7feaeb16  x64/d3d9.dll
  d912pxy: v2.0
  gw2radial: v1.2.4_al
installed:
  d3d9_wrapper: d3d9_wrapper
  arcdps: arcdps
  d912pxy: d912pxy
  gw2radial: gw2radial
disabled:
  d3d9_wrapper: false
  arcdps: false
  d912pxy: false
  gw2radial: false
wow you guys are fast

**Comment by alzatar** [comment]
When I say I deleted everything.  I deleted every file/folder in the GW2 folder except the .dat file and the gw2.exe.  Launched the game and let it rebuild the bin folder.  Turned off Windows defender and ran the gw2 add on manager app.  I do not have reshade reinstalled yet.

**Comment by fmmmlee** [comment]
"guys" is just me and I'm working on homework atm ;)

What does the contents of your /Guild Wars 2/addons folder look like?

**Comment by alzatar** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/60631895/73702854-0b8ff080-46bc-11ea-94ba-3738d6084930.png)
![Screenshot (3)](https://user-images.githubusercontent.com/60631895/73702868-12b6fe80-46bc-11ea-94cd-f4320fd39028.png)
![Screenshot (4)](https://user-images.githubusercontent.com/60631895/73702879-177bb280-46bc-11ea-99d4-4312f5fe5685.png)

**Comment by fmmmlee** [comment]
Nothing immediately identifiable as an issue to me; guessing from the lines of the log file you pasted:
```
[INFO] d3d9_wrapper | Loading custom lib from D3D_wrapper_custom_d3d9_lib_query
[INFO] d3d9_wrapper | d3d9 library failed to load
[INFO] core | Exiting, unloading core addon
[ERR] core | Some addons are not unloaded!
[INFO] core | Unloaded
```

There is some issue with the addon loading process, but I'm not sure what exactly that issue is. Also, before this issue happened last night did you install the latest version of d912pxy? It could be an issue with that latest version if this problem only cropped up after updating it. @megai2 you know if others  are experiencing this launch crash?

**Comment by alzatar** [comment]
No thats what I found strange.  I was playing, logged out.  Came back an hour later and boom, error.  I downloaded all the old files the .45 verison installed it. Reinstalled reshade, all previous files that I had already used about a week ago when I found out about mods for gw2 and still got the error.  I had not updated anything....

**Comment by alzatar** [comment]
There is a new geforce driver available as of today.  Im downloading it to see if it helps.

**Comment by alzatar** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/60631895/73703755-02ece980-46bf-11ea-807a-76cb52e2f376.png)
ya no such luck

**Comment by megai2** [comment]
log clearly says that it can't load d912pxy dll

1. update msvc redist https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
2. check your cpu for avx support, rn d912pxy needs it, maybe i will move back to non avx build soon

**Comment by alzatar** [comment]
Downloaded that file and now I can load in just fine.  Thank you !!
