### ISSUE TITLE
Addons doesn't load up within gw2

### ISSUE THREAD

**Issue by mex3semmen** [fmmmlee/GW2-Addon-Manager#15]
Acutally the addons doesn't load/ show up ingame. 
I completly reinstalled the game and the Addon-Manager. There isn't any error message, or generally any obviously failure i could firgure out.
The files you need are attached.
I also deleted the bin64 for gw2 autorecovery and then installed the UOAOM again, but it still didn't load the addons ingame.
I used this Manager since first release and now it doesn't work since 2 or 3 days.

Greeting from germany

-> [Files.zip](https://github.com/fmmmlee/GW2-Addon-Manager/files/4238882/Files.zip)

**Comment by ottobaer** [comment]
I had the same problem. The only solution for me was to delete the Profile Folder 

> "C:\Users\\AppData\Roaming\Guild Wars 2" 

redownload the Installer and reinstall the game to another Folder. 

NB: I kept the gw2.dat from the old install, so I didn't need to download the entire game again.

**Comment by mex3semmen** [comment]
Even that doesn't work^^ I'm getting totally mad.
I also found a similar discussion also about this addon:
https://github.com/fmmmlee/GW2-Addon-Manager/issues/10

I tried to manually implement the d3d9.dll but it didn't changed anything.
And also if I delete the whole manager and wanna install arcdps from the original homepage, it also doesn't show up, even with alt+shift+t.
I deleted gw2 the %appdata% and the whole ssd -> clean install.
No chance for me. Btw. the problem started, where i wanted to try out DVXK.
But after a clean reinstall it definitly shouldn't be the problem.

**Comment by mex3semmen** [comment]
Okay.
Don't know why, but I installed gw2 on my HDD and and now it works.
So maybe it's an issue about my SSD, but it worked fine since release of this manager.

So i guess the **solution is just to choose another drive**, wether a SSD or HDD, install gw2 and then the addon-manager again.
