### ISSUE TITLE
Request for adding GW2 SCT

### ISSUE THREAD

**Issue by Artenuvielle** [fmmmlee/GW2-Addon-Manager#19]
**Name**
GW2 SCT

**Website Link**
https://github.com/Artenuvielle/GW2-SCT/releases

**Anything else** 
I am the developer of that addon. If you need any help with it, feel free to reach out to me.

**Comment by megai2** [comment]
you can PR here with suitable config https://github.com/gw2-addon-loader/Approved-Addons
