### ISSUE TITLE
What is this code licensed under?

### ISSUE THREAD

**Issue by dlamkins** [fmmmlee/GW2-Addon-Manager#2]
After a quick look around, I didn't see what the code was licensed for included in the repo or in the README.

Has that been specified somewhere that I've just missed, or is the code currently unlicensed?

https://choosealicense.com/no-permission/

**Comment by fmmmlee** [comment]
Thanks for pointing this out! I put the MIT license on it now (yes, it was previously unlicensed); I must have forgotten back when I made the repo.

**Comment by dlamkins** [comment]
Thank you for the prompt fix!  🙂
