### ISSUE TITLE
Improve logs by printing unhandled exception call stack to log file

### ISSUE THREAD

**Issue by fmmmlee** [fmmmlee/GW2-Addon-Manager#21]
**Is your feature request related to a problem? Please describe.**
It's difficult to debug an issue on a user's machine when the log file is limited to the exception and inner exception.

**Describe the solution you'd like**
Print call stack to log file.

**Comment by smudge202** [comment]
Check Windows Event logs

**Comment by will-scc** [comment]
I just tried to create a pull request for this but am getting permission denied. I couldn't see any mention of requesting permission in the contributing guidelines. Am I missing something?

**Comment by fmmmlee** [comment]
Fork this repo and push the changes you wish to make into your fork, then make a pull request to merge that fork into the master branch of this repo
