### ISSUE TITLE
Killproof addon not showing kp of people in other instance

### ISSUE THREAD

**Issue by MikSki17** [fmmmlee/GW2-Addon-Manager#211]
As in title, it worked before, now it doesn't. Is there some box to check for it to work? I'm confused

**Comment by Zyian** [comment]
This GitHub page is strictly for the Addon Manager, not the individual addons themselves. You will want to join the Elite Insights discord https://discord.gg/T4kSbKJ5Sf
Where you can seek help in the #killproof-me-plugin channel.
