### ISSUE TITLE
Error: Index was out of range

### ISSUE THREAD

**Issue by Uinsart** [fmmmlee/GW2-Addon-Manager#218]
**Describe the bug**
Everytime I try to update the Addons, there is an Error Message

**To Reproduce**
Firing up the Addon Manager as Admin, clicking Update.
<img width="547" alt="2023-07-26 10_25_53-" src="https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/65364200/ffc2e63d-3ebc-40a5-beb4-a13f94c1bff6">

[log.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/12169759/log.txt)
[config.zip](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/12169767/config.zip)

**Comment by queenbee0717** [comment]
I too am getting this error

**Comment by pAvO66** [comment]
same here :-(

**Comment by Jadowdra** [comment]
I get this error only when trying to install "ArcDPS [WvW] Know thy enemy".

I've tested the following addons without trouble:

- ArcDPS
- ArcDPS Blish HUD Integration
- ArcDPS Boon Table
- ArcDPS Food Reminder
- ArcDPS Healing Stats
- ArcDPS Squad Ready Plugin
- ArcDPS Unofficial Extras
- Commander's Toolkit

I've also noticed that the addons installing after the one that gives me trouble are unselected when I re-open the manager.

**Comment by PhantomEkko** [comment]
> I get this error only when trying to install "ArcDPS [WvW] Know thy enemy".
> 
> I've tested the following addons without trouble:
> 
> * ArcDPS
> * ArcDPS Blish HUD Integration
> * ArcDPS Boon Table
> * ArcDPS Food Reminder
> * ArcDPS Healing Stats
> * ArcDPS Squad Ready Plugin
> * ArcDPS Unofficial Extras
> * Commander's Toolkit
> 
> I've also noticed that the addons installing after the one that gives me trouble are unselected when I re-open the manager.

I was going to type im getting this error aswell but yeah Unchecked WvW Know Thy Enemy and it worked ty hope we will get an update for that plugin soon 🤔

**Comment by FunTimeCoding** [comment]
Its fixed now for me since 11 hours ago, the new version of know thy enemy was released: https://github.com/typedeck0/Know-thy-enemy/releases

**Comment by Uinsart** [comment]
> Its fixed now for me since 11 hours ago, the new version of know thy enemy was released: https://github.com/typedeck0/Know-thy-enemy/releases

Can confirm. Now it runs through without an error.
