### ISSUE TITLE
Cant install addons 

### ISSUE THREAD

**Issue by MiTxGam3r** [fmmmlee/GW2-Addon-Manager#227]
**Describe the bug**
Fresh download of latest version of ad on manager
Fresh install of Gw2
Cant locate the bin folder even though I have provided the path in the software.

![image_2024-06-24_212845829](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/43783749/f15e1c68-ebbd-4a77-b45a-58b447662de6)

Was working fine when I was on windows 10.

**Comment by MiTxGam3r** [comment]
[log.txt](https://github.com/user-attachments/files/15956429/log.txt)

**Comment by Invisi** [comment]
Change the game path to `G:\Program Files\Guildwars 2\Guild Wars 2` and try again

**Comment by knoxfighter** [comment]
You have to provide the path to the Guild Wars 2 folder and NOT the bin64 folder.
Just remove the `\bin64` from the path and it will work

**Comment by MiTxGam3r** [comment]
> G:\Program Files\Guildwars 2\Guild Wars 2

I have tried the path and it still wont work

**Comment by knoxfighter** [comment]
What is the error this time?

**Comment by MiTxGam3r** [comment]
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/43783749/0e01a4de-ea5f-4d3e-b845-a993fe38a707)

**Comment by knoxfighter** [comment]
Send a screenshot of your gw2 folder please

**Comment by MiTxGam3r** [comment]
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/43783749/3a7b394f-64e6-4865-ab0a-ecd2a562af0d)


> Send a screenshot of your gw2 folder please

**Comment by MiTxGam3r** [comment]
got me beat tbh. Had no issues when i was on windows 10. GW2 was also not installed on the C drive

**Comment by knoxfighter** [comment]
And the path you selected is really `Guild Wars2\Guild Wars 2\`?
Also your dat has only 245MB, something seems off with your gw2 installation.

**Comment by MiTxGam3r** [comment]
Not sure if its just decided to work or if it was me removing the extra GW2 folder but it has decided to work now. Down side the game now has 600k files to download again XD

**Comment by MiTxGam3r** [comment]
> And the path you selected is really `Guild Wars2\Guild Wars 2\`? Also your dat has only 245MB, something seems off with your gw2 installation.

Cheers for your assistance

**Comment by knoxfighter** [comment]
you're welcome :)
