### ISSUE TITLE
Installed addon doesn't load on game launch, new computer

### ISSUE THREAD

**Issue by DerpPizza** [fmmmlee/GW2-Addon-Manager#228]
See title, got a new laptop. It's lenovo LOQ 15 series that's out around 2023 so have new software, win11 and everything (if that needs to be considered). Fresh installed Guild Wars 2 and the latest Addon Manager. Tried plenty of stuff for hours but it just doesn't want to load any addons when I start the game. Manual installation of arcdps works completely fine.

I'm not sure where I can find the config.ini file, all I have in Addon Manager folder is GW2 Addon Manager.exe.config so i'll attach that.

would appreciate any help!

[GW2 Addon Manager.exe.config.txt](https://github.com/user-attachments/files/16098872/GW2.Addon.Manager.exe.config.txt)

**Comment by knoxfighter** [comment]
Which addons have you installed?
Please send a screenshot of your gw2, and addons folder (with filesizes).
Please send the file `gw2al_log.txt`

**Comment by DerpPizza** [comment]
I installed arcdps, arcdps boon table, and gw2 radial.
idk how to show size of folder on the list so I screenshotted each size's.

![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/c3995dca-ba1e-4d99-8c79-b1d179fc0c43)
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/8a843789-86a1-4130-9b99-1bb4462590ea)
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/c152f53b-3519-4985-bd47-5b4ad1cf4371)
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/605fd277-bf62-4ba0-b275-ad6563e20050)
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/f3ce4f3f-0857-4259-9fdb-9f7a55f0537d)
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/f7b5ab58-9b18-4cb3-82e4-c47c4d897a16)

[gw2al_log.txt](https://github.com/user-attachments/files/16099213/gw2al_log.txt)

**Comment by knoxfighter** [comment]
Does arcdps work (with the addon loader/manager)? if no, send the file `/addons/arcdps/arcdps.log`.
Rightclick `d3d11.dll` and select the Unlock button.

**Comment by DerpPizza** [comment]
nope, installing arc ONLY with Addon Manager doesn't work as well. 
Strange, I don't have arcdps log in the folder, only these two, and I have started the game already so log should've been made? 
![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/5c609104-8941-4880-a76e-2dd6ab050c6c)

also I don't see unlock after rightclicking d3d11.dll

**Comment by knoxfighter** [comment]
delete dxgi.dll in bin64

Do you use any of the following?
- BitDefender
- groupy
- Citrix Workspace (v22 or later)
- mydesk shield
- Nvidia's GeForce Overlay
- ASUS GPU Tweak III, Afterburner, RTSS (RivaTuner Statistics Server) or any other GPU overclock/control software
- [medal](<https://medal.tv/>)
- (Razer Cortex)

**Comment by DerpPizza** [comment]
done, deleted dxgi in bin64. Should I delete dxgi inside cef (inside bin64) too?

No I dont use any of that programs.  Checked app list on settings just in case they added any of those software when I bought the laptop yesterday as well, and I don't see any on that list installed.

thanks for helping btw

**Comment by knoxfighter** [comment]
no, keep the dxgi inside cef, that one is most likely needed.

Install the latest C++ redistributable.
Page: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
Direct Download: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by DerpPizza** [comment]
did, also updated net framework 4.8.1 since the requirements asks for it. Unfortunately still doesn't work

**Comment by knoxfighter** [comment]
Still no arcdps log? I'm getting out of ideas :(

**Comment by DerpPizza** [comment]
Oh wait might found the solution. When you told me to delete dxgi, it reminds me of Delta's arcdps site (https://www.deltaconnected.com/arcdps/) saying optionally you can rename d3d11.dll to dxgi.dll so I renamed the d3d11 in the gw2 directory into dxgi, had to replace the already existing dxgi and when I run the client these two error message pops out 

![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/1e9e941b-6607-4351-93a6-06c968b7e0eb)

![image](https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/90187793/c2e41e2e-8aad-4d21-8bd6-47cb3924665a)

BUT,

It works! I got the initial setup popup for arcdps and gw2radial. Really appreciate the ideas though because otherwise I would've given up and settled with only radial and no arc. Thx!

should I keep this ticket open incase anyone know what's up with that error message? or should I close and open a different ticket 🤔

**Comment by DerpPizza** [comment]
So.. I lied, apparently the game only worked once with that "stopgap measure". Now whenever I open the game it just crashes after I tried selecting my toons in character select.  Asking for help once more.

I'll also attach gw2al_log:

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r541
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] core | Unloading core addon
[INFO] core | Unloaded
r addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi

thanks in advance!

**Comment by DerpPizza** [comment]
Silly! found the fix myself. Apparently my pc refuses to automatically switch to my GPU. So I've been running gw2 on integrated graphic all this time and I think the addons don't like that. So if anyone is having issues with getting multiple addons to run, make sure to check your GPU control panel (Nvidia control panel in my case) and see which graphic card you're using to run the game.
