### ISSUE TITLE
Incomplete Buildpad Compatibility

### ISSUE THREAD

**Issue by fmmmlee** [fmmmlee/GW2-Addon-Manager#25]
**Target Branch:** `buildpad-compat-wip`
### Description
BuildPad handles updates by itself; on an update the plugin filename changes. This renders the system used to handle file operations for other addons unsuitable for it and will cause crashes after the plugin updates itself.

### Implementation
Buildpad should be skipped during the update process (since it does it by itself). Due to the changes to filename, the plugin cannot be tracked in the configuration file. Instead, when the user tries to delete/disable the plugin, the filename should be found by scanning the /arcdps/ folder for a .dll file with 'buildpad' in the name. I believe disabling, at the moment, places a plugin in a specifically named folder (in this case it would be /buildpad/) in the application resources. Enabling for buildpad can then mean just transplanting whatever dll is in that folder back into /arcdps/.

### Development Considerations
This involves changes to all of the update code to insert checks for buildpad. Be sure to avoid making any changes that affect the updating or file management for all other addons if at all possible. If such changes are necessary or beneficial in the long run, be sure to update the project board and issue to indicate what changes are going to be performed and any adjustments that will need to be made throughout the rest of the application as a result.

#### Additional context
Another fairly frequently requested feature.

**Comment by greaka** [comment]
I think you should do something generic, like a setting in the template file `skip_update` or `self_updating` or something like that. or maybe an enum `update_mode` to have multiple values possible.

**Comment by fmmmlee** [comment]
Agreed. I think I'll go the route of adding an optional list to the end of the `update.yaml` files that's just for additional flags, such as the ones you mentioned above. Then, where relevant, the manager can just check `config.optional_flags` (or whatever it gets called) to see if it needs to do anything special.

**Comment by fmmmlee** [comment]
Added `obscured-filename` flag to the buildpad yaml and a handler for it since buildpad's filename is not exposed in the URL. Also adapted the enable, disable, and delete functions to work for buildpad but have not tested them yet.

**Comment by fmmmlee** [comment]
Fixed, merged changes, and released in 1.1.0.
