### ISSUE TITLE
Can't launch game anymore (crash on launcher startup)

### ISSUE THREAD

**Issue by DesolatePsyche** [fmmmlee/GW2-Addon-Manager#27]
Title in a nutshell.

Anyhow, downloaded ur addons manager, installed all mods, clicked finish.

Started my GW2 ..and it insta crashes during launcher loading.

Added in files the log it gives.
[new 1.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/4564890/new.1.txt)

**Comment by DesolatePsyche** [comment]
UPDATE1: managed to re-launch the launcher & game by deleting bin64 folder. Will try to test what exactly breaks the whole thing..

**Comment by fmmmlee** [comment]
If it's d912pxy making a crash when you launch the game then this might help since it's required by the latest d912pxy: 
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
