### ISSUE TITLE
Make it check for the addon chain loader d3d9.dll every time you update

### ISSUE THREAD

**Issue by TybaIt** [fmmmlee/GW2-Addon-Manager#33]
Because removing it temporarely for a patch and it doesn't redownload it  when you want to activate addons again unless I remove/reset the config.yaml.

**Comment by marcustyphoon** [comment]
This should probably be checked when updating addons as well, in case they were deleted without removing config.yaml.

**Comment by TybaIt** [comment]
Good job fixing this issue.
