### ISSUE TITLE
Feature Request: Buttons for navigating back and to start the game.

### ISSUE THREAD

**Issue by TybaIt** [fmmmlee/GW2-Addon-Manager#36]
**Is your feature request related to a problem? Please describe.**
When a patch comes and you need to reconsider disabling addons you have to reopen the program because there is just a "Finish" button. You need to have a way to navigate back to the index page after updating. I recommend this button to be right above or to the left of the Finish button (like the "Back" button in setups wizards.)

**Describe the solution you'd like**
A button to navigate back to the landing page left to the Finish button.

A "Launch" button to the right of the "Back" button (which launchs the game with `-autologin` command line argument. This is just for people having saved login information.)

The "Finish" button would end up to the most right and should be renamed to "Close" for context clarity.

[Back][Launch][Close]

you could also make a tick box (check box) that appears on the page after updating. "Launch the game when closing". The value should be saved and default should be unchecked. This way you can omit a dedicated "Launch" button if the space turns out to be too small for three buttons.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by will-scc** [comment]
I'm looking at this; it seems pretty simple. I think a checkbox option is better than an additional button as it also means the user's preference can be saved in config which is nice.

@fmmmlee I'm thinking we'd need to add an additional "exe_name" to `UserConfig` and set this as part of `Configuration.DetermineSystemType()`. How do you feel about the assumption that the exe is always called "Gw2-64.exe" or "Gw2.exe"? Obviously it'd be wrapped in a try/catch but I can't see an elegant way to determine the correct exe as it could be named anything... And there could be any number of other exe in the game path directory.

**Comment by fmmmlee** [comment]
Somewhere in the user config there's already a field for system type since the game folder might be either bin or bin64 depending on the user's processor. Could probably just use that to determine executable name, i.e. `exename = (userconfig.binfolder=="bin" ? "Gw2.exe" : "Gw2-64.exe")`
Sorry for bad formatting, on mobile

**Comment by fmmmlee** [comment]
And I think it's fair to assume it's one of those two, since the user would have to go out of their way to get it to be anything else.

**Comment by will-scc** [comment]
That would work too.

Only reason I thought about going down the route of an additional user config field was if it gets used elsewhere it would save repeating that logic. I'd also want to add a bool to save the users choice anyway...
________________________________

**Comment by fmmmlee** [comment]
Makes sense. I suppose the most versatile solution would be to have it determine the exe name using the above logic the first time it's used and then store that in a field in the config file, which could be manually edited in a settings dialog. Speaking of which, I really should make a dedicated settings menu; I can't just keep appending stuff to the little menu under the add-on list...

**Comment by will-scc** [comment]
I'll make a pull request for this later today with the additional user config field added, but it could (probably should) be moved into a separate settings menu at a later date.

**Comment by fmmmlee** [comment]
Merged and drafted a release for 1.2.0; I marked it as prerelease for now since I haven't tested the features myself but if no one encounters any issues with it I'll set it to be a full release in a few days. Thanks again @will-scc for implementing this!

**Comment by TybaIt** [comment]
Exactly what I was suggesting. Good job btw
