### ISSUE TITLE
Can't seem to Uninstall so I can use GW2 Hook again

### ISSUE THREAD

**Issue by ravenclaw82** [fmmmlee/GW2-Addon-Manager#37]
It would be very helpful to have a way to uninstall in case something isn't working properly or you don't want to use it anymore.
I can't for the life of me figure out how to get rid of everything so I can put the addons that I want and use GW2 Hook again.
I have tried uninstalling GW2 and getting rid of everything and when I reinstall and put the .dll's in the bin64 folder they don't work and I get the little log file saying that the addons that come with UOAM didn't load.

**Comment by fmmmlee** [comment]
clean install button in latest version now does this.
