### ISSUE TITLE
(Minor UI bug) "All addons have been removed"

### ISSUE THREAD

**Issue by marcustyphoon** [fmmmlee/GW2-Addon-Manager#40]
Selecting **"Configuration Options"**  -> **"Reset to clean install"** -> **"No"** results in an "All addons have been removed" message. No addons are actually removed, so this is just a UI problem.

**Comment by AdaLollA** [comment]
can confirm. does nothing more than scare you for a second that your arc setup has been removed. No actual removal / change in any files tho.

**Comment by fmmmlee** [comment]
fixed with v1.2.1
