### ISSUE TITLE
Describe the addon loader's basic functionality in README.md or a visible link

### ISSUE THREAD

**Issue by marcustyphoon** [fmmmlee/GW2-Addon-Manager#42]
**Problem**
The addon loader method makes the normal installation instructions provided by addons incorrect, including breaking (at the moment) the install.exe provided with d912pxy. This isn't a problem, but the fact that many users don't realize things aren't the "normal" way is. 

Currently this is only documented in the bottom of [/wiki/Previously-Installed-Addons](https://github.com/fmmmlee/GW2-Addon-Manager/wiki/Previously-Installed-Addons), which took me a good hour or so to find the first time I installed this and broke it, and that doesn't actually describe how it works.

There's no way to get most non-technical users to understand this stuff, and that's fine; hopefully, they never have to. However...

**Solution**
...something in the readme that says _"hey, we moved the addon .dlls to /addons"_ would probably help a ton with troubleshooting. At least fewer people would overwrite the addon loader with arcdps maybe?

**Comment by fmmmlee** [comment]
added relevant info to wiki under "installation" section.
