### ISSUE TITLE
Doesn't download if addons were deleted manually

### ISSUE THREAD

**Issue by Zaidya** [fmmmlee/GW2-Addon-Manager#45]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
I deleted the addon folder by hand/moved it to my desktop after an update of gw2, so the client' doesn't crash because of arcdps. After that I moved it back to it's location and tried to update with the addon manager. Later Arcdps didn't appear in my game (I know the hotkeys). So I removed the addon folder again, tried to reinstall with the manager, manager does nothing, because it still thinks, addons are installed. So I marked the addons again, and clicked delete inside the manager, to reinstall after again. Didn't work either. Even if I move the filled addon folder back, and wanna delete with the manager then, it doesn't work. 

**To Reproduce**
1. delete/move installed addons
2. (maybe) move them back
3. try to update newest version or reinstall missing addons
4. try to delete with manager / with or without addonfolder

**Additional context**
Hi, if the addon manager would firstly check, if the addons are really there, that might help? 

**don't forget to attach the config file to the issue**
"We don't suport that file type" so here is the written  config.yaml:

application_version: v1.1.1
loader_version: v0.2
bin_folder: bin64
isupdate: true
game_path: C:\Program Files\Guild Wars 2
current_addon_list: 6a47cfc36ceb3030259d7b6d97cc321f6f4270e5
default_configuration:
  d3d9_wrapper: false
version:
  d3d9_wrapper: v1.1
  d912pxy: v2.2
  arcdps: >
    0dcfd96c3b511f45baf89e1b97f3df40  d3d9.dll
  arcdps_boontable: v1.0
installed:
  d3d9_wrapper: d3d9_wrapper
  d912pxy: d912pxy
  arcdps: arcdps
  arcdps_boontable: arcdps_boontable
disabled:
  d3d9_wrapper: false
  d912pxy: false
  arcdps: false
  arcdps_boontable: false

**Comment by fmmmlee** [comment]
Since the plugin names aren't necessarily constant and more than one plugin can be in each folder (due to codependent Arc plugins) checking for plugins would be convoluted to implement, but in the next update I've added a "force redownload" button that will redownload and install any addons that are selected. Would this be an adequate solution for you?

**Comment by Zaidya** [comment]
Hi Matthew,
I just wanted to let you know that there is this behavior. I've helped myself with the button, wich resets the AddOn Manager to default. That worked fine, too :) I don't know if a force button is neccessary now.
wish you a nice week
Zaidya

________________________________
Von: Matthew Lee <notifications@github.com>
Gesendet: Dienstag, 11. August 2020 05:16
An: fmmmlee/GW2-Addon-Manager <GW2-Addon-Manager@noreply.github.com>
Cc: Zaidya <Evanescence-Krissy@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [fmmmlee/GW2-Addon-Manager] Doesn't download if addons were deleted manually (#45)


Since the plugin names aren't necessarily constant and more than one plugin can be in each folder (due to codependent Arc plugins) checking for plugins would be convoluted to implement, but in the next update I've added a "force redownload" button that will redownload and install any addons that are selected. Would this be an adequate solution for you?

**Comment by fmmmlee** [comment]
No problem, it's probably good to have anyway, so I'll keep it in.
-Matthew
