### ISSUE TITLE
Windows marks exe as a trojan

### ISSUE THREAD

**Issue by xsdf** [fmmmlee/GW2-Addon-Manager#47]
Windows defender marked exe as a trojan: Trojan:Win32/Emali.A!cl

Threat link:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fEmali.A!cl&threatid=2147728322

**Comment by fmmmlee** [comment]
Submitted to Microsoft SI as a falsely flagged application, response pending. For peace of mind, if you prefer you can use the [artifacts](https://ci.appveyor.com/project/fmmmlee/gw2-addon-manager/build/artifacts) built directly from the latest source code.

**Comment by fmmmlee** [comment]
Interestingly enough if I scan just the application folder it's fine, but when it's zipped up it flags it as a trojan.

**Comment by fmmmlee** [comment]
None of my other releases get flagged and neither do the latest build artifacts. I'll just publish a new release since there doesn't seem to be this issue with them.

**Comment by fmmmlee** [comment]
Unflagged by Microsoft, looks like that's it. That fixes this for the v1.2.1 release, and none of the other releases are flagged so should be ok.

![incorrectflag](https://user-images.githubusercontent.com/30479162/90216627-eccd8d80-ddb3-11ea-9ca4-6a292bb0418c.JPG)
