### ISSUE TITLE
Can't get the .exe to work

### ISSUE THREAD

**Issue by programgirl** [fmmmlee/GW2-Addon-Manager#49]
I've just downloaded the files, and unpacked them.

I have the .exe open, with the addon I want selected, and I ended up editing the game path manually as I couldn't use Select Directory.

Everything is greyed out, and it's telling me that the bin64 path is incorrect. I've taken a snapshot: https://imgur.com/a/kfDNdPl

**Comment by fmmmlee** [comment]
If you set the path to `E:\Program Files\Guild Wars 2` (no bin64), it should work.

**Comment by programgirl** [comment]
Thank you, that worked. Any idea why my buttons are greyed out rather than red?

**Comment by fmmmlee** [comment]
Which buttons? The ones in the addon manager are all styled grey/blue if I recall correctly.

**Comment by programgirl** [comment]
Ah, must be an older image I saw - the buttons were all red.
