### ISSUE TITLE
Addon Manager doesn't(?) put a .dll in root folder

### ISSUE THREAD

**Issue by marcustyphoon** [fmmmlee/GW2-Addon-Manager#5]
None of my addons will load without a copy of d3d9.dll in C:\Program Files\Guild Wars 2, which as far as I can tell from a quick google is just true for some people's setups, or something? Anyway, making a copy there as part of the update process would be great.

(Unless it already does, and I broke the tool when I tried disabling d912pxy just now and had to delete the config file and start over. But assuming that's not the cause...)

**Comment by fmmmlee** [comment]
A d3d9.dll is supposed to be created as long as any addon is installed, either for gw2radial, arcdps or d912pxy. Can I see a copy of your config file?

**Comment by marcustyphoon** [comment]
One gets created in C:\Program Files\Guild Wars 2\bin64 just fine. There's no copy in C:\Program Files (x86)\Guild Wars 2\, however.

<details>
  <summary>config.ini!</summary>
```
{
  "application_version": "v0.4.4",
  "bin_folder": "bin64",
  "isupdate": false,
  "arcDPS": "d3d9.dll",
  "arcDPS_buildTemplates": "d3d9_arcdps_buildtemplates.dll",
  "gw2Radial": "d3d9_chainload.dll",
  "d912pxy": "d912pxy.dll",
  "game_path": "C:\\Program Files (x86)\\Guild Wars 2",
  "default_configuration": {
    "arcdps": false,
    "gw2radial": false,
    "d912pxy": false,
    "arcdps_bhud": false,
    "arcdps_mechanics": false
  },
  "version": {
    "arcdps": "11f0b4081d6410a62b90bbf4afaae901  x64/d3d9.dll\n",
    "gw2radial": null,
    "d912pxy": null,
    "arcdps_bhud": null,
    "arcdps_mechanics": "39af47dea0d955e181aea205c0ec6a7c\r\n"
  },
  "installed": {
    "arcdps": "d3d9.dll",
    "gw2radial": "d3d9_chainload.dll",
    "d912pxy": "d912pxy.dll",
    "arcdps_bhud": null,
    "arcdps_mechanics": "d3d9_arcdps_mechanics.dll"
  },
  "disabled": {
    "arcdps": false,
    "gw2radial": false,
    "d912pxy": false,
    "arcdps_bhud": false,
    "arcdps_mechanics": false
  }
}
```
</details>

**Comment by fmmmlee** [comment]
Oh, ok. I think I may know what's causing this; hopefully I'll push a fix today or tomorrow.

**Comment by fmmmlee** [comment]
Just to be sure, are saying you need a d3d9.dll file in the Guild Wars 2 folder:
![gamefolder](https://user-images.githubusercontent.com/30479162/64294841-a37a8a00-cf24-11e9-8fa7-dbe65bd1919d.JPG)



or in the bin subfolder:

![bin64 folder](https://user-images.githubusercontent.com/30479162/64294726-62827580-cf24-11e9-942c-1e87537d0aad.JPG)

**Comment by marcustyphoon** [comment]
In the Guild Wars 2 folder. 

I'm not actually sure why? I first started doing it a long time ago when it was suggested to make addons load when launching the game from GW2LaunchBuddy.

**Comment by fmmmlee** [comment]
That's very interesting; I've never had to do that before (and I assume most other people don't or the issue would have come up earlier). Is it maybe a requirement for GW2Launchbuddy but not the regular game?

**Comment by marcustyphoon** [comment]
I wouldn't be surprised if it's related to that, yeah. My impression at the time was that all of the 3rd-party launchers required it there, but for some reason even if I just launch gw2-64.exe it seems to be required for mine now.

Yeah, that would be perfect!

**Comment by fmmmlee** [comment]
Sounds good; what d3d9.dll needs to be in the game folder? Can it be an empty file, or does it have to be for a specific plugin/set of plugins/all of them get put in that directory?

**Comment by marcustyphoon** [comment]
Great question! I just tested now: just the d3d9.dll copied from /bin64 works (so, in my case, arcdps); no file doesn't load arcdps, and an empty file crashes on launch with 

![Untitled](https://user-images.githubusercontent.com/8336245/64295886-551aba80-cf27-11e9-902c-11477bf637cd.png)

I did load the game earlier with arcdps and d912pxy both installed via the addon manager and that worked fine without changing anything. And chainloading bgdm and arc back in the day only required d3d9.dll to be copied as well.

**Comment by fmmmlee** [comment]
that's good to know, I'll put it on the list of things to add. There's probably going to be significant changes in 0.5.0 (particularly to the config file, I'm switching to using .yaml for simplicity) but this will be on the feature list as well. You can close this issue if you want or leave it open as an extra reminder for me to implement the feature :)

**Comment by marcustyphoon** [comment]
Awesome, thanks! I'll probably clean install GW2 on another system when 0.5.0 comes out to see if any of the other stuff I was seeing is just my install being weird :)
