### ISSUE TITLE
launcher crash after installing only d912pxy

### ISSUE THREAD

**Issue by bloocow** [fmmmlee/GW2-Addon-Manager#50]
I have no addons to GW2. 
After reset clean install, I installed d912pxy only & exited.
Then run launcher, it crashes with error msg below:

*--> Crash <--*
Assertion: Failed to load Coherent DLL. Error code: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(58)
App: Gw2-64.exe 
Pid: 6180
BaseAddr: 00007FF7C6610000
ProgramId: 101
Build: 105843
When: 2020-09-01T14:28:55Z 2020-09-01T22:28:55+08:00
Uptime:   0 days  0:00:02
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: 49b7b7ee
IpAddr: 192.168.1.17
Processors: 6 [GenuineIntel:6:14:10]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 11321MB/16301MB  69%
Paged:    24158MB/31646MB  76%
Virtual:  134213204MB/134217727MB  3%
Load: 30%
CommitTotal:   7487MB
CommitLimit:  31646MB
CommitPeak:   30160MB
SystemCache:   4622MB
HandleCount:  66230
ProcessCount:   144
ThreadCount:   1957

*--> Process Memory <--*
Private:          103MB
WorkingSet:       100MB
PeakWorkingSet:   212MB
PageFaults:    270852

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    78.86       6248        
Uncategorized           42.60       4533        
Programmer Data         29.81       960         
I/O                     29.22       514         
Archive                 27.89       38          
Collide Havok           6.45        755         
Collide                 6.45        755         
File Service            1.24        12          
Collections             0.32        210         
Dictionary              0.24        41          
Networking              0.11        14          
Asset Service           0.09        459         
Event                   0.07        3           
Game                    0.05        56          
BTree                   0.03        18          
Engine                  0.02        12          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Install                 0.00        30          
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           42.60       4533        
Archive                 27.89       38          
Collide Havok           6.45        755         
File Service            1.24        12          
Dictionary              0.24        41          
Networking              0.11        9           
Asset Service           0.09        459         
Event                   0.07        3           
Collections             0.04        150         
BTree                   0.03        18          
Game                    0.03        46          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Engine                  0.01        6           
Install                 0.00        30          
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           

*--> DllList <--*
00007FF7C6610000 - C:\Guild Wars 2\Gw2-64.exe
00007FFC12600000 - C:\Windows\SYSTEM32\ntdll.dll
00007FFC10AC0000 - C:\Windows\System32\KERNEL32.DLL
00007FFC0F7A0000 - C:\Windows\System32\KERNELBASE.dll
00007FFC11890000 - C:\Windows\System32\USER32.dll
00007FFC0F5D0000 - C:\Windows\System32\win32u.dll
00007FFC10A20000 - C:\Windows\System32\GDI32.dll
00007FFC0FA50000 - C:\Windows\System32\gdi32full.dll
00007FFC10400000 - C:\Windows\System32\msvcp_win.dll
00007FFC104A0000 - C:\Windows\System32\ucrtbase.dll
00007FFC122A0000 - C:\Windows\System32\ADVAPI32.dll
00007FFC11720000 - C:\Windows\System32\msvcrt.dll
00007FFC12350000 - C:\Windows\System32\sechost.dll
00007FFC124A0000 - C:\Windows\System32\RPCRT4.dll
00007FFC11650000 - C:\Windows\System32\WS2_32.dll
00007FFC105A0000 - C:\Windows\System32\WINTRUST.dll
00007FFC0F560000 - C:\Windows\System32\MSASN1.dll
00007FFC0F600000 - C:\Windows\System32\CRYPT32.dll
00007FFC10A10000 - C:\Windows\System32\PSAPI.DLL
00007FFC087F0000 - C:\Windows\SYSTEM32\VERSION.dll
00007FFC10740000 - C:\Windows\System32\ole32.dll
00007FFC0BB50000 - C:\Windows\SYSTEM32\WTSAPI32.dll
00007FFC0D400000 - C:\Windows\SYSTEM32\WINMM.dll
00007FFC112E0000 - C:\Windows\System32\combase.dll
00007FFC0FBF0000 - C:\Windows\System32\bcryptPrimitives.dll
00007FFC121D0000 - C:\Windows\System32\OLEAUT32.dll
00007FFC11A30000 - C:\Windows\System32\SHELL32.dll
00007FFC0CE30000 - C:\Windows\SYSTEM32\WINMMBASE.dll
00007FFC0F580000 - C:\Windows\System32\cfgmgr32.dll
00007FFC123F0000 - C:\Windows\System32\shcore.dll
00007FFC0FC70000 - C:\Windows\System32\windows.storage.dll
00007FFC0F4C0000 - C:\Windows\System32\profapi.dll
00007FFC0F4F0000 - C:\Windows\System32\powrprof.dll
00007FFC0F4B0000 - C:\Windows\System32\UMPDC.dll
00007FFC10A60000 - C:\Windows\System32\shlwapi.dll
00007FFC0F540000 - C:\Windows\System32\kernel.appcore.dll
00007FFC0F780000 - C:\Windows\System32\cryptsp.dll
00007FFC052C0000 - C:\Windows\SYSTEM32\MSACM32.dll
00007FFBFEDC0000 - C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.1016_none_cf6529a13ef454b2\gdiplus.dll
00007FFBFEA60000 - C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1016_none_73b3274ad815f571\COMCTL32.dll
00007FFC03E10000 - C:\Windows\SYSTEM32\USP10.dll
00007FFBFEF70000 - C:\Windows\SYSTEM32\MSIMG32.dll
00007FFBF9870000 - C:\Windows\SYSTEM32\Secur32.dll
00007FFC0EEE0000 - C:\Windows\SYSTEM32\CRYPTBASE.DLL
00007FFC0F3A0000 - C:\Windows\SYSTEM32\SSPICLI.DLL
00007FFC11620000 - C:\Windows\System32\IMM32.DLL
00007FFBEC440000 - C:\Windows\SYSTEM32\dbghelp.dll
00007FFC0F750000 - C:\Windows\System32\bcrypt.dll
00007FFC0E110000 - C:\Windows\SYSTEM32\dxcore.dll
00007FFC0D770000 - C:\Windows\system32\uxtheme.dll
00007FFC087C0000 - C:\Windows\SYSTEM32\cryptnet.dll
00007FFC10980000 - C:\Windows\System32\imagehlp.dll
00007FFC0E880000 - C:\Windows\system32\rsaenh.dll
00007FFC0E0C0000 - C:\Windows\SYSTEM32\gpapi.dll
00007FFC12120000 - C:\Windows\System32\clbcatq.dll
00007FFC0E500000 - C:\Windows\SYSTEM32\ntmarta.dll
00007FFC02F60000 - C:\Windows\system32\napinsp.dll
00007FFC02F40000 - C:\Windows\system32\pnrpnsp.dll
00007FFC0ED10000 - C:\Windows\System32\mswsock.dll
00007FFC0EA60000 - C:\Windows\SYSTEM32\DNSAPI.dll
00007FFC10730000 - C:\Windows\System32\NSI.dll
00007FFC0EA20000 - C:\Windows\SYSTEM32\IPHLPAPI.DLL
00007FFC03EE0000 - C:\Windows\System32\winrnr.dll
00007FFC0CE00000 - C:\Windows\system32\NLAapi.dll
00007FFBFB7F0000 - C:\Windows\system32\wshbth.dll
00007FFC09CA0000 - C:\Windows\System32\fwpuclnt.dll
00007FFC088F0000 - C:\Windows\System32\rasadhlp.dll
00007FFC111A0000 - C:\Windows\System32\msctf.dll
00007FFC04FB0000 - C:\Windows\System32\TextInputFramework.dll
00007FFC0CE60000 - C:\Windows\System32\CoreMessaging.dll
00007FFC0AA70000 - C:\Windows\System32\CoreUIComponents.dll
00007FFC0B020000 - C:\Windows\SYSTEM32\wintypes.dll
00007FFC0A010000 - C:\Windows\SYSTEM32\WindowsCodecs.dll
00007FFBFC5F0000 - C:\Windows\system32\explorerframe.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\Windows\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 6.2.18362.1 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x1600 <--*

*--> Trace <--*
----------------------------------------------------
Theres more code after this but I didn't paste it.

**Comment by fmmmlee** [comment]
Do you have the latest MS Visual C++ Redist installed? See https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by aggieh** [comment]
I have exactly the same problem

**Comment by bloocow** [comment]
After updating the MS Visual C++, resolved the issue.
