### ISSUE TITLE
Any addon installed causes gw2 launcher to crash

### ISSUE THREAD

**Issue by crimmsonwind** [fmmmlee/GW2-Addon-Manager#52]
[config.zip](https://github.com/fmmmlee/GW2-Addon-Manager/files/5165123/config.zip)

On Windows 10 64 bit, I cannot install and run any addon, otherwise the launcher crashes. I have tried them individually, and ArcDPSm GW2Radial, and d912pxy all give the same result. I have done "Reset to Clean Install" between each. I have also deleted the whole bin64 folder and let gw2 recreate it just in case there was anything left over.

"*--> Crash <--*
Assertion: Failed to load Coherent DLL. Error code: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(58)
App: Gw2-64.exe 
Pid: 9836
BaseAddr: 00007FF6A4D80000
ProgramId: 101
Build: 105843
When: 2020-09-02T22:29:35Z 2020-09-02T18:29:35-04:00
Uptime:   0 days  0:00:02
Flags: 0
DumpFile: Crash.dmp"

**Comment by fmmmlee** [comment]
Do you have the latest Microsoft Visual C++ Redistributable installed?

**Comment by crimmsonwind** [comment]
Just did that and some miscellaneous updates. It works now. I am, indeed, a dumbass.
