### ISSUE TITLE
Unable to locate Game Path 

### ISSUE THREAD

**Issue by ParaChrona** [fmmmlee/GW2-Addon-Manager#53]
**Describe the bug**
First off, the "Select Directory" button does nothing for me, at all. I've tried running in and out of admin, no change. I've manually located the path of Guild Wars 2 bin 64, which is on the D drive for me, manually input, and still the same error. Not sure what to do here. The Manager says that it is unable to locate the Guild wars 2 bin64, despite being extracted into, on, and around - as well as having the location put in manually. Not sure if this is a bug or what. 

The error message reads "Unable to locate Guild Wars 2 /bin/ or /bin64/ folder. Please verify Game Path is correct."

**Comment by fmmmlee** [comment]
Try leaving off /bin64/ when putting in the path; the manager adds that in itself

**Comment by ParaChrona** [comment]
Just tried that. Unfortunately, no change.

**Comment by ParaChrona** [comment]
I believe I've solved my issue. Kind of a dumb mistake but I'll post the solution that worked for me here in case any others are having the same issue. 

Guild Wars 2 is a 64 bit program, so it should be installed in the Program Files folder, NOT the Program Files x86 folder. After moving the entire "Guild Wars 2" folder to the proper "Program Files" folder, then manually pasting the location (D:\Program Files\Guild Wars 2), the addon worked like a charm. Again, noob mistake, but I've seen many others running into this same issue - perhaps without knowing the difference between the two folders. Cheers!

**Comment by fmmmlee** [comment]
Thanks for the info, glad you got it working!

**Comment by Kaievi** [comment]
I am having a similar issue. Both my Program Files and Program Files 86 are on my (C:) drive but my guild wars 2 was on my (D:) drive because my (C:) drive is near full. So I tried copying my Program Files over to the (D:) drive and then placing my Guild Wars 2 in there to see if it would work with (D:\Program Files\Guild Wars 2) as the game path but still the same error. Please help!

**Comment by ShDmitriy** [comment]
I've solved my issue. Edit string <GamePath> in the config.xml in the Addon-Manager folder - <GamePath>C:\Program Files\Guild Wars 2</GamePath> to your path like <GamePath>D:\Guild Wars 2</GamePath>

**Comment by gormleymark** [comment]
Having this issue also. GW2 is installed on my SSD with path E:\Guild Wars 2. Tried @ShDmitriy solution but the <GamePath> is already set correctly.

**Comment by hamidr144** [comment]
I had the same issue. In my case I just checked that the config.xml has a proper game path and restarted the Addon-Manager.
