### ISSUE TITLE
Addon Manager fails to Open Gw2-64.exe

### ISSUE THREAD

**Issue by PoppaGritz** [fmmmlee/GW2-Addon-Manager#54]
### Please attach a copy of config.yaml or config.ini to the issue.

https://drive.google.com/drive/folders/19biyNNQYMQFAmVMjh1louUDho5s7SW3f?usp=sharing

**Describe the bug**

I followed [https://youtu.be/B86Zq3a4GrI](url) this video step by step. Everything appears to work but when I close the addon manager and have it open the game I get an error saying it cant find the Gw2-64.exe.

I do have the game installed on my D:\ drive and not the normal C:\.

**Comment by Donskussen** [comment]
i have the same problem, .exe won't start and crashes after install of any modd. I also have it installed on D:\ and not on a C:\. 
[GW2 addon crash.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/5178228/GW2.addon.crash.txt)

**Comment by fmmmlee** [comment]
@Donskussen make sure you have the latest MS Visual C++ installed: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

@PoppaGritz Interesting, everything checks out in the config file and the screenshots you posted so I'll have to have a look at the function that tries to launch the game. I'm studying for the GRE this weekend but next week I should be able to look into this further.

**Comment by PoppaGritz** [comment]
@Donskussen Just downloaded and installed latest MS Visual C++, still having the same issue. Thank you for the suggestion.

@fmmmlee Thank you, I can play without just wanted to try the DX12 lol. I have not yet tried to install the addons manually for this game. Let me know if you find out what I am doing wrong...any help is greatly appreciated. I like the ease of the addon manager though! Great work!

**Comment by PoppaGritz** [comment]
@fmmmlee  So tonight I was messing around with it to see if I could get it to work. I reset the Addon Manager to a clean install. Only installed the DX12 one, hit UPDATE, then close. Got the same error so I gave up and opened the game, it still loaded up the mod. 

I tried to add the arcDPS mod, hit UPDATE, then close. Got same error but only the arcDPS mod loaded up. Closed everything went to addon manager only checked DX12 mod etc... the arcDPS mod still loaded up only even when not checked in the addon manager (still installed though).

Clean reset addon manager and only installed DX12 mod, still got error but when game loaded up the DX12 mod loaded. closed and opened game multiple times with just this mod installed and checked, worked every time. 

DX12 mod is working for now! Will give any other updates when I get them.

Not sure if this helps at all, if you need any info from me let me know.

**Comment by Donskussen** [comment]
For some reason after i hit update, it also reinstalled the d3d9.dll (in the bin64 folder). Delete it after installing modds and it worked for me.

**Comment by fmmmlee** [comment]
Going back through old issues to sort things out, it looks like you got this one sorted out @PoppaGritz but if it's not resolved feel free to reopen this issue.
