### ISSUE TITLE
Cannot find bin64, correct dir

### ISSUE THREAD

**Issue by tb0n3zz** [fmmmlee/GW2-Addon-Manager#56]
* Select directory button doesn't work.
* Can't find my bin64 dir when I edit the game dir manually.
* config.yaml has just part of the dir `C:\games` and no executable name.
* When I edit config.yaml in a text editor and add the full path to game_path: then the next run of the Manager works and can find my game.
* Unzipped clean and reproduced consistently.

Minor but figured I'd report it, thank you for your work!

![Screenshot 2020-09-13 084231](https://user-images.githubusercontent.com/25313681/93019777-c0698480-f59e-11ea-9f47-7ca00d74fb96.png)
![Screenshot 2020-09-13 084737](https://user-images.githubusercontent.com/25313681/93019778-c495a200-f59e-11ea-8e85-180623d8f397.png)
[config.zip](https://github.com/fmmmlee/GW2-Addon-Manager/files/5214190/config.zip)

**Comment by Altiahad** [comment]
Have this been fixed yet or someone found a workaround?

**Comment by fmmmlee** [comment]
@Altiahad Sorry for my silence recently, it looks like for now manually editing the game_path field of your config.yaml file should work according to @tb0n3zz ,  hopefully I'll get out a release with #59 integrated sometime soon so that'll fix this properly.
