### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TXJ1123** [fmmmlee/GW2-Addon-Manager#58]
*--> Crash <--*
Assertion: Failed to load Coherent DLL. Error code: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(58)
App: Gw2-64.exe 
Pid: 3500
BaseAddr: 00007FF737B60000
ProgramId: 101
Build: 106328
When: 2020-09-16T11:40:35Z 2020-09-16T06:40:35-05:00
Uptime:   0 days  0:00:03
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: fba08a0c
IpAddr: 192.168.1.237
Processors: 8 [GenuineIntel:6:14:9]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical:  7150MB/12173MB  58%
Paged:     7492MB/14029MB  53%
Virtual:  134213239MB/134217727MB  3%
Load: 41%
CommitTotal:   6536MB
CommitLimit:  14029MB
CommitPeak:    9736MB
SystemCache:   7475MB
HandleCount:  71054
ProcessCount:   184
ThreadCount:   2126

*--> Process Memory <--*
Private:          109MB
WorkingSet:       102MB
PeakWorkingSet:   215MB
PageFaults:    229901

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    78.93       6101        
Uncategorized           42.68       4531        
Programmer Data         29.80       815         
I/O                     29.28       505         
Archive                 27.95       27          
Collide Havok           6.45        755         
Collide                 6.45        755         
File Service            1.24        12          
Collections             0.25        73          
Dictionary              0.24        41          
Networking              0.11        14          
Asset Service           0.09        461         
Event                   0.07        3           
Game                    0.05        56          
Engine                  0.02        12          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Install                 0.00        30          
BTree                   0.00        6           
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           42.68       4531        
Archive                 27.95       27          
Collide Havok           6.45        755         
File Service            1.24        12          
Dictionary              0.24        41          
Networking              0.11        9           
Asset Service           0.09        461         
Event                   0.07        3           
Game                    0.03        46          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Collections             0.01        25          
Engine                  0.01        6           
Install                 0.00        30          
BTree                   0.00        6           
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           

*--> DllList <--*
00007FF737B60000 - C:\Program Files\Guild Wars 2\Gw2-64.exe
00007FFBDF520000 - C:\WINDOWS\SYSTEM32\ntdll.dll
00007FFBDDEC0000 - C:\WINDOWS\System32\KERNEL32.DLL
00007FFBDC910000 - C:\WINDOWS\System32\KERNELBASE.dll
00007FFBDD800000 - C:\WINDOWS\System32\USER32.dll
00007FFBDC790000 - C:\WINDOWS\System32\win32u.dll
00007FFBDE500000 - C:\WINDOWS\System32\GDI32.dll
00007FFBDC560000 - C:\WINDOWS\System32\gdi32full.dll
00007FFBDD4C0000 - C:\WINDOWS\System32\msvcp_win.dll
00007FFBDCBC0000 - C:\WINDOWS\System32\ucrtbase.dll
00007FFBDEDF0000 - C:\WINDOWS\System32\ADVAPI32.dll
00007FFBDDBB0000 - C:\WINDOWS\System32\msvcrt.dll
00007FFBDF3E0000 - C:\WINDOWS\System32\sechost.dll
00007FFBDECD0000 - C:\WINDOWS\System32\RPCRT4.dll
00007FFBDE000000 - C:\WINDOWS\System32\WS2_32.dll
00007FFBDC700000 - C:\WINDOWS\System32\WINTRUST.dll
00007FFBD5E70000 - C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFBDC3F0000 - C:\WINDOWS\System32\MSASN1.dll
00007FFBDAF80000 - C:\WINDOWS\SYSTEM32\WTSAPI32.dll
00007FFBD9F80000 - C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFBDC7C0000 - C:\WINDOWS\System32\CRYPT32.dll
00007FFBDD720000 - C:\WINDOWS\System32\PSAPI.DLL
00007FFBDDA50000 - C:\WINDOWS\System32\ole32.dll
00007FFBD9FC0000 - C:\WINDOWS\SYSTEM32\winmmbase.dll
00007FFBDE1C0000 - C:\WINDOWS\System32\combase.dll
00007FFBDD580000 - C:\WINDOWS\System32\cfgmgr32.dll
00007FFBDD440000 - C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFBDD650000 - C:\WINDOWS\System32\OLEAUT32.dll
00007FFBDE5E0000 - C:\WINDOWS\System32\SHELL32.dll
00007FFBDE530000 - C:\WINDOWS\System32\shcore.dll
00007FFBDCCC0000 - C:\WINDOWS\System32\windows.storage.dll
00007FFBDC410000 - C:\WINDOWS\System32\profapi.dll
00007FFBDC440000 - C:\WINDOWS\System32\powrprof.dll
00007FFBDC3E0000 - C:\WINDOWS\System32\UMPDC.dll
00007FFBDF480000 - C:\WINDOWS\System32\shlwapi.dll
00007FFBDC490000 - C:\WINDOWS\System32\kernel.appcore.dll
00007FFBDD560000 - C:\WINDOWS\System32\cryptsp.dll
00007FFB9D6C0000 - C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFBD2190000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.1082_none_cf6c86c73eed9f8f\gdiplus.dll
00007FFBD1C40000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1082_none_73b2803ad816b43c\COMCTL32.dll
00007FFBD8500000 - C:\WINDOWS\SYSTEM32\USP10.dll
00007FFBD4EA0000 - C:\WINDOWS\SYSTEM32\MSIMG32.dll
00007FFBC9420000 - C:\WINDOWS\SYSTEM32\Secur32.dll
00007FFBDBDA0000 - C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
00007FFBDC2C0000 - C:\WINDOWS\SYSTEM32\SSPICLI.DLL
00007FFBDDE80000 - C:\WINDOWS\System32\IMM32.DLL
00007FFBDACF0000 - C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFBDC760000 - C:\WINDOWS\System32\bcrypt.dll
00007FFBDAEF0000 - C:\WINDOWS\SYSTEM32\dxcore.dll
00007FFBDA2E0000 - C:\WINDOWS\system32\uxtheme.dll
00007FFB7E190000 - C:\WINDOWS\System32\DriverStore\FileRepository\ki126950.inf_amd64_fa7f56314967630d\igd9dxva64.dll
00007FFBDD630000 - C:\WINDOWS\System32\imagehlp.dll
00007FFBDB740000 - C:\WINDOWS\system32\rsaenh.dll
00007FFBDD9A0000 - C:\WINDOWS\System32\clbcatq.dll
00007FFBDB3C0000 - C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFBD86B0000 - C:\WINDOWS\system32\napinsp.dll
00007FFBD7E90000 - C:\WINDOWS\system32\pnrpnsp.dll
00007FFBDBBD0000 - C:\WINDOWS\System32\mswsock.dll
00007FFBDB920000 - C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFBDDEB0000 - C:\WINDOWS\System32\NSI.dll
00007FFBDB8E0000 - C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
00007FFBD8530000 - C:\WINDOWS\System32\winrnr.dll
00007FFBD82A0000 - C:\WINDOWS\system32\NLAapi.dll
00007FFBD7390000 - C:\WINDOWS\system32\wshbth.dll
00007FFBD4EE0000 - C:\WINDOWS\System32\fwpuclnt.dll
00007FFBD1330000 - C:\Windows\System32\rasadhlp.dll
00007FFBDE070000 - C:\WINDOWS\System32\msctf.dll
00007FFBD1290000 - C:\WINDOWS\System32\TextInputFramework.dll
00007FFBD2660000 - C:\WINDOWS\System32\CoreUIComponents.dll
00007FFBD9EA0000 - C:\WINDOWS\System32\CoreMessaging.dll
00007FFBD7880000 - C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFBD17D0000 - C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
00007FFBC0000000 - C:\WINDOWS\system32\explorerframe.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.18362.1049 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x13c4 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff7`37cf318c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37cf320b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`3869557d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`3800120d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37fff747 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37f5a6ab 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37f591b2 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37cd05e7 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37ec368e 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37ec193e 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37ec15b9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37ec2c4f 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37ec0fbc 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37ce9dc1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`37e7a5a1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffb`dded7bd4 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffb`df58ce51 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff7393b2938 rcx=0000009dca3fe7d0
rdx=00007ff7393b2938 rsi=000000000000003a rdi=0000009dca3fed00
rip=00007ff737cf312d rsp=0000009dca3fe770 rbp=0000009dca3ff080
 r8=000000000000003a  r9=00007ff737b60000 r10=0000009dca3fe9f6
r11=0000009dca3fec30 r12=0000000000000002 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF7393B2918  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rbx +0 00007FF7393B2938  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rbx+32 00007FF7393B2958  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
rcx-32 0000009DCA3FE7B0  00007ff7`37cf312d 0000009d`ca3fe770 0000009d`ca3ff080 00000007`0000002d 
rcx +0 0000009DCA3FE7D0  00000000`00000020 00000000`ffffffff 00000288`00000000 0000009d`ca3fe9f6 
rcx+32 0000009DCA3FE7F0  00007f00`00000002 00000000`00000000 00009f80`0010000f 0053002b`002b0033 
rdx-32 00007FF7393B2918  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rdx +0 00007FF7393B2938  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rdx+32 00007FF7393B2958  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
 r9 +0 00007FF737B60000  00000003`00905a4d 0000ffff`00000004 00000000`000000b8 00000000`00000040 
 r9+32 00007FF737B60020  00000000`00000000 00000000`00000000 00000000`00000000 00000170`00000000 

*--> Code <--*
00007ff7`37cf310d  488bf941 8bf0488d 0d46e8cf 01488bda H..A..H..F...H..
00007ff7`37cf311d  e80e73fe ff488d4c 2460ff15 0b623f01 ..s..H.L$`...b?.
00007ff7`37cf312d  488b8424 58010000 4c8d0574 91400148 H..$X...L..t.@.H
00007ff7`37cf313d  89442440 4885db48 8b8424f8 00000044 .D$@H..H..$....D
00007ff7`37cf314d  8bce4889 4424484c 0f45c348 8b842400 ..H.D$HL.E.H..$.
00007ff7`37cf315d  01000048 8bd74889 44245033 c9488d44 ...H..H.D$P3.H.D

*--> Stack <--*
0000009d`ca3fe770  0000009d`ca3fed2d 00000000`00000200 00000000`0000002d 00000000`00000000 -.?.............-...............
0000009d`ca3fe790  0000009d`ca3fe7b0 0000009d`ca3fe7d0 00000000`00000000 0000009d`ca3fe758 ..?.......?.............X.?.....
0000009d`ca3fe7b0  00007ff7`37cf312d 0000009d`ca3fe770 0000009d`ca3ff080 00000007`0000002d -1.7....p.?.......?.....-.......
0000009d`ca3fe7d0  00000000`00000020 00000000`ffffffff 00000288`00000000 0000009d`ca3fe9f6  .........................?.....
0000009d`ca3fe7f0  00007f00`00000002 00000000`00000000 00009f80`0010000f 0053002b`002b0033 ........................3.+.+.S.
0000009d`ca3fe810  00000202`002b002b 00007ffb`bb0b8654 00000000`00000000 00000000`7ffe0385 +.+.....T.......................
0000009d`ca3fe830  00000000`00000040 00000288`38840c68 00000288`38840c20 00000000`00000001 @.......h..8.... ..8............
0000009d`ca3fe850  0000009d`ca3fe7d0 00007ff7`393b2938 00007ff7`393b2938 0000009d`ca3fe770 ..?.....8);9....8);9....p.?.....
0000009d`ca3fe870  0000009d`ca3ff080 00000000`0000003a 0000009d`ca3fed00 00000000`0000003a ..?.....:.........?.....:.......
0000009d`ca3fe890  00007ff7`37b60000 0000009d`ca3fe9f6 0000009d`ca3fec30 00000000`00000002 ...7......?.....0.?.............
0000009d`ca3fe8b0  00000000`00000000 00000000`00000000 00000000`00000000 00007ff7`37cf312d ........................-1.7....
0000009d`ca3fe8d0  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009f80 ................................
0000009d`ca3fe8f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe910  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe930  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe950  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe970  00000000`00000000 00000000`00000000 746e6572`65686f43 6c6c642e`34364955 ................CoherentUI64.dll
0000009d`ca3fe990  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe9b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe9d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fe9f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fea10  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fea30  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fea50  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000009d`ca3fea70  00000000`00000000 00007ffb`df5607bd 00000288`38afe5f0 00000013`ca3fee00 ..........V........8......?.....
0000009d`ca3fea90  00000000`00000004 00000288`38afe990 00000288`38a9bb00 00007ffb`1508e8f5 ...........8.......8............
0000009d`ca3feab0  00000288`38a59500 0000002d`02000002 00000000`00000000 00000288`388d9430 ...8........-...........0..8....
0000009d`ca3fead0  00000000`00000100 00000288`36840150 00000000`00000000 00000000`00000001 ........P..6....................
0000009d`ca3feaf0  00000000`000000dc 00000288`36840000 00000288`36840000 00007ffb`df5660b9 ...........6.......6.....`V.....
0000009d`ca3feb10  00000288`36848090 00000000`00000600 00000288`388da501 00007ffb`000000dc ...6...............8............
0000009d`ca3feb30  00000000`00000100 00000288`3dcd6010 00000000`00000400 00007ffb`df561d61 .........`.=............a.V.....
0000009d`ca3feb50  00000288`36840000 00000288`36840000 00000288`3dcd6000 00000000`00000080 ...6.......6.....`.=............

*--> Error Logs <--*
11:40:35Z Coherent DLL load filepath: C:\Program Files\Guild Wars 2\bin64\CoherentUI64.dll
Crashed at 11:40:35Z

**Comment by fmmmlee** [comment]
Check and make sure you have the latest visual c++ redist version:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by TXJ1123** [comment]
That fixed it.  Thank you.
