### ISSUE TITLE
Game insta-crashes after updating

### ISSUE THREAD

**Issue by Bon3rdaddy** [fmmmlee/GW2-Addon-Manager#6]
Hello.  I just updated GW2 as well as used the addon manager to update Arcdps, Buildtemplates, and d912x.  After installing updates the game would no longer launch form launcher.  I deleted bin64, d912x file and reinstalled all 3 again.  Game will launch but now Arcdps and buildtemplates are no longer loading.  When I try to remove them through the addon manager I get an error stating it cannot access the bin64 folder.

**Comment by fmmmlee** [comment]
Got a copy of config.ini? I'm in class right now but will check this out when I can. 

Just an update on the progress of next version, chainloading is as annoying for us developers as it is for you and thankfully the next update will hopefully resolve 99% of problems you guys (just users in general) have been having with the plugins. It won't be out for a couple weeks yet, though, so I'll try to find out what the problem is here.

Just making sure, you're getting the "cannot access bin64" error while the game isn't running?

**Comment by Bon3rdaddy** [comment]
[config2.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/3677971/config2.txt)

There is the config.  And yes it was giving me that error with the game closed and the file closed as well.

**Comment by fmmmlee** [comment]
Try running in admin mode? (right click, run as admin)

**Comment by Bon3rdaddy** [comment]
I run both the addon manager and GW2 in admin already =-/

**Comment by fmmmlee** [comment]
The configuration file looks fine; can I see a screenshot of your bin64 folder? If the config file is accurate then everything should be behaving normally, but it's not so I assume somehow the plugins got messed up.

**Comment by Bon3rdaddy** [comment]
![Bin64](https://user-images.githubusercontent.com/56044592/65992690-8b732900-e444-11e9-9920-fe6eaf4a2f94.png)

So I un-installed and reinstalled Addon Manager.  Deleted Bin64 and d912x folders.  Reinstalled arcdps and d912x through Addon manager.  Game loads in now, arcdps pops up with an error saying unable to locate or something, and the buildtemplates will not launch when using the command.

Not sure what my issue is lol.

**Comment by fmmmlee** [comment]
arc's "unable to locate" errors typically come after a game patch when arc hasn't yet been updated. I don't believe you or I have any control over that. I haven't been experiencing those errors, which is odd, but in any case that's an arc thing and not a manager thing. Is d912pxy working?

**Comment by fmmmlee** [comment]
OH just read this in your original post "I just updated GW2" that would cause the arc issue if Delta hasn't patched it yet.

**Comment by Bon3rdaddy** [comment]
I can never tell if d912pxy is ever actually working or not lol.  Is there an easy way to tell?

**Comment by fmmmlee** [comment]
Character portraits get broken, both in character select and ingame.

**Comment by Bon3rdaddy** [comment]
Broken in what way?  I haven't noticed that.  The only thing I have seen after installing it or updating it is  everything turns blue for a while while it's "loading."

**Comment by fmmmlee** [comment]
I'll screenshot when I get out of class.

**Comment by Bon3rdaddy** [comment]
Don't even worry man I never noticed the portraits before but they are definitely broken.  Thanks for all the help today!  It seems deleting everything and reinstalling has fixed the issue I was having.  Looking forward to that future update so this whole process is less of a pain!

**Comment by fmmmlee** [comment]
All right, no problem! Hopefully everything will fall into place for the changes pretty soon.
