### ISSUE TITLE
Checkboxes aren't saved.

### ISSUE THREAD

**Issue by TybaIt** [fmmmlee/GW2-Addon-Manager#60]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
Checkboxes of installed addons aren't saved.  The check boxes should be checked if an addon is installed or disabled when a session restarts.

**To Reproduce**
N/A

**Additional context**
N/A

**don't forget to attach the config file to the issue**

**Comment by Draeggiar** [comment]
Did you try the "Set default" option from configuration menu ? 
![image](https://user-images.githubusercontent.com/18702335/93804614-ddf5b880-fc46-11ea-88c5-4a8fd0a8bbb7.png)
It saves information wich checkboxes are selected by default, wich I also find a llittle confusing. I think that more intuitive would be if installed addons were selected.

I proposed this change on my branch [here](https://github.com/Draeggiar/GW2-Addon-Manager/commit/793345db0c6849b5cd8e90af5644e278464b162c).

**Comment by TybaIt** [comment]
haha I knew it but forgot about and yeah I think it should save the check box of all addons that are not uninstalled by default.

**Comment by fmmmlee** [comment]
Closing but will consider setting the addons selected at first run as default in next version.
