### ISSUE TITLE
d3d9.dll creates error when starting the gw2 launcher

### ISSUE THREAD

**Issue by Cryotype** [fmmmlee/GW2-Addon-Manager#61]
Hey there, 
i used the addon manager Launcher on gw2 i installed arcdps and since than the launcher does not open anymore and i get the following error (copied it to editor)
[errord3d9.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/5254456/errord3d9.txt)

i mangaed to delete the d3d9.dll and start the game again but i would love to play with the addon -.- any idea what the issue could be?
I tried the fixes i found around the net.
i use the 1.22 UOAOM.
i unistalled all the other contained addon parts (radial, boontable, mechnics, etc.. (Taco still runs smotly though) and tried installing them on their own the only thing that does not give me the error is radial.
i also updated the c++ just to be safe enven though the d12 addon is uninstalled (https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by PopSonny** [comment]
yup, same to me, i have a pc and a laptop, I installed the addon on the pc and it worked, but if i try to make it work on my laptop i get the error.

**Comment by PopSonny** [comment]
> yup, same to me, i have a pc and a laptop, I installed the addon on the pc and it worked, but if i try to make it work on my laptop i get the error.

well after some search in the other post I found out that maybe the C++ visual isnt the latest one, I installed it and now it works.
https://support.microsoft.com/ro-ro/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Cryotype** [comment]
Tried it saldy it did not help -.- bbut ty for the idea!

**Comment by Yack0** [comment]
Hi, i have the same problem as OP and also have the latest C++ visual. Tried a repair on the c++ 2015_2019 and it didn't change anything. If d3d9.dll is deleted launcher runs again, but no addons will.
[Crash_details.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/5279338/Crash_details.txt)

CoherentUI64.dll seems to be the source of the crash, although i don't get why.
I tried to delete the addons, also tried a forced redownload, none of them allowed me to launch the game. I checked .net framework and i seem to have the latest version. I am short of ideas, if you have any solution that would allow me to try what looks like an awesome addon manager, i would highly appreciate it. Thanks !

**Comment by Yack0** [comment]
I found a "fix" ! maybe this can help other people. It is not exactly a fix to be honnest, it is just that i had downloaded and installed the latest version of "vcredistx**86**" for visual c++, but it seems i needed the "vcredistx**64**" version for it to work correctly. After downloading, installing and rebooting computer, no crash anymore, instant fix. Didn't have to delete the x86 version. Hope this helps other people too, the manager is awesome and i'm really happy i can use it, thanks for sharing this tool !

**Comment by WoolfordH** [comment]
Installing vc_redist linked by @PopSonny fixed this for me

**Comment by WormyTheGamer** [comment]
I have the same issue but none of the solutions here worked for me.

**Comment by fmmmlee** [comment]
@WormyTheGamer I'd recommend trying addons out one by one by themselves to nail down which one is causing your issue. Once you find out which one(s) are causing errors then you can go to their specific pages to file an issue.

This has come up fairly often so I'll add something about this to the wiki.

**Comment by sweetlion93** [comment]
hey guys any fix for this?
