### ISSUE TITLE
"Start GW2 when closing" should not affect the window's close button (top right corner)

### ISSUE THREAD

**Issue by TybaIt** [fmmmlee/GW2-Addon-Manager#64]
Again, thanks for adding that feature. I just noticed a small issue when checking for updates.
The feature I requested before that was added recently (Start GW2 when closing) should not affect the close button on the top right corner. For many users that button is used to cancel out.
Ex. case: Checking for later gameplay.  Being able to comfortably close *UOAOM* without having to uncheck the tickbox to start GW2 and therefore saving new settings and having to re-tick the box later on.
Also noting that its context - by design - is grouped with the big custom button control labeled with "Close" and not with the X button top-right,

**Comment by fmmmlee** [comment]
Good point, added a new handler and pointed the x button to it. Will be included in next release, whenever that happens to be.
