### ISSUE TITLE
Error with assembly PresentationFramework.Aero2 when launching on win7

### ISSUE THREAD

**Issue by DaPiePiece** [fmmmlee/GW2-Addon-Manager#7]
Googled the issue, and apparently the assembly that fails to load doesn't exist on windows 7 which I'm currently using. Is there a work around?

**Comment by fmmmlee** [comment]
Thanks for pointing this out; I'll change the references in the next release to try to compensate for this.

**Comment by fmmmlee** [comment]
I removed the references involved so once I get the next release out, everything should work properly on Win7. Closing for now, but if after the next release the problem persists, go ahead and reopen the issue.
