### ISSUE TITLE
404 during installation

### ISSUE THREAD

**Issue by ShreddyMarz** [fmmmlee/GW2-Addon-Manager#8]
The installer 404s when installing ArcDPS + ArcDPS Mechanics + d912pxy. The file it references is ArcDPS' build templates, which apparently has been removed as of 10-17-2019, https://www.deltaconnected.com/arcdps/ - It won't let me install ArcDPS, or any of the other addons because of this.

**Comment by ALERTua** [comment]
https://www.reddit.com/r/Guildwars2/comments/dhspu0/arcdps_build_templates_to_be_disabled_tomorrow/ :(

**Comment by fmmmlee** [comment]
Hotfixed in v0.4.5
