### ISSUE TITLE
Unable to locate /bin/ or /bin64/

### ISSUE THREAD

**Issue by DanHouston** [fmmmlee/GW2-Addon-Manager#83]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
I updated the path to my GUILD WARS 2 folder and when I hit the UPDATE button it says:
"Unable to locate Guild Wars 2 /bin/ or /bin64/ folder. Please verity Game Path is correct.

**To Reproduce**
My game path is:
C:\!games\Guild Wars 2

**Additional context**
I suspect it can't handle the ! in the path. Hoping that would be an easy fix in the code.

**don't forget to attach the config file to the issue**

**Comment by BotFrixxy** [comment]
I'm experiencing the same issue while having It installed on D:\Guild Wars 2 which is my hdd. I could do some testing and reinstall gw2 on my ssd, but I'd prefer not to.

I'll continue to run some tests myself.

**Comment by BotFrixxy** [comment]
I finally got it to work by reinstalling the manager, and restarting my pc.
Not sure what the issue actually was, but it's working fine for me now. Maybe it just didn't get properly installed until the restart happend!

**Comment by DanHouston** [comment]
Mine is working as well after a restart of my computer. Not sure why that would be needed, but it is working. :)

**Comment by JoeDavies42** [comment]
In case anyone finds this in the future, I've just experienced this and tried to find a solution, but couldn't see anything online. The solution was to manually add a \ to the end of the folder path, it wasn't doing it when selecting the folder in the interface, but I was able to add is to the end of the path in the config.xml file.

**Comment by joshcodestheworld** [comment]
> In case anyone finds this in the future, I've just experienced this and tried to find a solution, but couldn't see anything online. The solution was to manually add a \ to the end of the folder path, it wasn't doing it when selecting the folder in the interface, but I was able to add is to the end of the path in the config.xml file.

This worked, thanks!

**Comment by azdog90** [comment]
actually the worst addon to setup hands down.

games on my c drive, pathing is all correct and still cannot locate the folder lol.

**Comment by howar31** [comment]
can't locate my game install under "C:\Games\Guild Wars 2\"

**Comment by JuanClopez** [comment]
Same here cant finf bin 64 on my path but its there im going to restart
