### ISSUE TITLE
Taco

### ISSUE THREAD

**Issue by xfouloux** [fmmmlee/GW2-Addon-Manager#9]
Hi,

first awesome job, i was in the process of trying to do a tool like that, but you did real good.

Also, can Taco Be added then ? with at least these 2 POI packs

http://tekkitsworkshop.net/index.php/gw2-taco/download
https://www.heinze.fr/taco/?lang=en (it has DE,FR and EN, would be awesome to be able to select lang)

Regards

**Comment by fmmmlee** [comment]
TaCO has its own installation process and isn't a plugin/addon for the game, rather an external application that interfaces with it, so it's not really in scope for now. I'm not ruling it out for the future, but it's unlikely to be added.

**Comment by xfouloux** [comment]
Yup, i just saw on reddit you said the same.

It's only tedious to keep taco updated, and POI too

I've forked your project, and will see if time and skill allow me to add that =)
Cause it is only a matter of checking taco version diff from PC and Site, and for POI use taco://URI using the taco.exe

**Comment by fmmmlee** [comment]
Best of luck!

**Comment by bcaddy** [comment]
I'd like to +1 this. TaCO integration along with Tekkit would be amazing.
